plugins {
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'com.diffplug.spotless' version '7.0.2'
}

version = '1.0.5-forge-1.20.1'
group = 'com.mapsyncer'

base {
    archivesName = 'mapsyncer'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://maven.aliyun.com/repository/public' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    flatDir { dirs 'libs' }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        configureEach {
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${project.buildDir}/createSrgToMcp/output.srg"
            args '--mixin.config', 'mapsyncer.mixins.json'
        }

        client {
            workingDirectory project.file('runClient')
        }

        server {
            workingDirectory project.file('runServer')
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.5'

    implementation 'org.slf4j:slf4j-api:2.0.9'

    compileOnly fg.deobf('xaeroworldmap-forge-1.20.1:xaeroworldmap-forge-1.20.1:1.45.0')
    runtimeOnly fg.deobf('xaeroworldmap-forge-1.20.1:xaeroworldmap-forge-1.20.1:1.45.0')

    compileOnly 'org.spongepowered:mixin:0.8.5'
    compileOnly 'org.ow2.asm:asm:9.7'

    runtimeOnly fg.deobf('packet_profiler:packet_profiler:1.0.0')
}

jar {
    manifest {
        attributes 'MixinConfigs': 'mapsyncer.mixins.json'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all']
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

spotless {
    java {
        palantirJavaFormat('2.50.0')
    }
}
