
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

systemProp.net.minecraftforge.gradle.check.certs=false

org.gradle.java.installations.auto-download=true

org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.20.8-hotspot

org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-17.0.20.8-hotspot

mod_id=mapsyncer
mod_version=1.0.5
mod_group_id=com.mapsyncer

forge_1201_version=47.3.0
minecraft_1201_version=1.20.1

g1_jar_suffix=1.20
g1_minecraft_range_forge=[1.20,1.20.2)
